// <auto-generated />
using System;
using GenesisMegaDeskRazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenesisMegaDeskRazor.Migrations
{
    [DbContext(typeof(GenesisMegaDeskRazorContext))]
    [Migration("20231031013131_FourthUpdate")]
    partial class FourthUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenesisMegaDeskRazor.Models.DeskQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdditionalSqInchCost")
                        .HasColumnType("float");

                    b.Property<double>("BaseDeskPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DrawerCost")
                        .HasColumnType("float");

                    b.Property<double>("RushOrderCost")
                        .HasColumnType("float");

                    b.Property<double>("SurfaceMaterialCost")
                        .HasColumnType("float");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DeskQuote");
                });
#pragma warning restore 612, 618
        }
    }
}
